### ISSUE TITLE
NPM package needs to be published with the fix from issue 2

### ISSUE THREAD

**Issue by helenb** [clearnote01/readability#4]
The fix for https://github.com/clearnote01/readability/issues/2 has not made it's way into the published NPM package at https://www.npmjs.com/package/text-readability - the latest version there was published a year ago. Please can this be published as I would love to use this package, but at the moment the bug from that issue is preventing me.

**Comment by clearnote01** [comment]
Yepp, you were right @helenb I hadn't take published the release in npm, I have published 1.0.5 with your PR as well as the previous fix. I haven't had to use this project since one time (when I made it). Not sure if you are still interested in this project, but I would gladly add you as a maintainer in npm.

**Comment by helenb** [comment]
Thank you @clearnote01 - I probably don't know enough about the underlying logic to be a maintainer. I've just used this on a build that needed some text analysis. Thanks for merging my fixes and republishing the package.
